### ISSUE TITLE
Create decko-memcached.service file, and run this at a non-default port

### ISSUE THREAD

**Issue by jernst** [decko-commons/decko-ubos#1]
This way, decko and other apps running memcached do not get into each other's way.

**Comment by ethn** [comment]
Do I understand correctly that you have done this?

**Comment by jernst** [comment]
I decided to leave this as-is for the time being, and get the rest running. Once we have it running, adding it is simple enough. Cuts down on the moving parts for the time being ... hope that's okay.

**Comment by jernst** [comment]
This is partially addressed now by 8cf18907215f4f9b00872aaed6fa0fac3b151f60: now several deckos on the same machine can use the same memcached and not get into each other's way. This does not address other apps wanting to use memcached.

**Comment by jernst** [comment]
Closing this in favor of #14.
