### ISSUE TITLE
CSS problem with expand_less

### ISSUE THREAD

**Issue by jernst** [decko-commons/decko-ubos#12]
On the first page after a new install: 2px solid back line around expand_less.

![screenshot_20181015_222851](https://user-images.githubusercontent.com/874785/46981935-db3cd100-d0c9-11e8-9d21-ee7058135740.png)

This seem to only occur when Decko is installed not at the root of the site. And it is aggressive HTTP/browser caching, so it may require a hard refresh to get it to show up.

**Comment by jernst** [comment]
I think this is done, right @ethn?

**Comment by ethn** [comment]
yes. this meant the assets weren't generating properly. they are now.
