### ISSUE TITLE
Use non-default memcache port for decko

### ISSUE THREAD

**Issue by jernst** [decko-commons/decko-ubos#14]
@ethan: where in the decko setup would one specify a non-standard memcached port?
This then needs to be used:
* in the `decko-memcached.service` file
* in Decko itself
* added to the table here: https://ubos.net/docs/developers/well-known-ports.html#to-allocate-a-single-port-used-by-all-appconfigurations-of-an-app

**Comment by ethn** [comment]
Sorry so slow on this.  Very little dev time on trip, then got sick at home.

memcached is managed by the "dalli" gem and is configured (to use the standard 11211 port) here: https://github.com/decko-commons/decko-ubos/blob/master/decko/tmpl/application.rb.tmpl

I'm not sure what a decko-memcached.service file is supposed to look like, but I can dig into this tomorrow.

**Comment by jernst** [comment]
I already created https://github.com/decko-commons/decko-ubos/blob/master/decko/systemd/decko-memcached.service, it just needs to be customized.

**Comment by jernst** [comment]
This is done.
