### ISSUE TITLE
Implement logrotate

### ISSUE THREAD

**Issue by jernst** [decko-commons/decko-ubos#17]
... for `/var/log/decko/<appconfigid>/production.log`.

**Comment by ethn** [comment]
Is this on my plate or yours?

**Comment by jernst** [comment]
Either :-)

**Comment by ethn** [comment]
I'll have a look. Have you done this elsewhere?

**Comment by jernst** [comment]
Here are some examples:
* https://ubos.net/docs-yellow/developers/logging.html#if-journald-based-logging-is-not-possible
* https://github.com/uboslinux/ubos-mattermost/blob/master/mattermost/tmpl/logrotate.tmpl

It's very simple -- just one file to add -- except that causing the app to write to the newly created file (after rotate) might require some kind of restart: you can see it in the `postrotate` section. Not sure how to do that for Decko.

This is important because otherwise sooner or later `/var/log/...` fills up, and so without it, the site needs manual maintenance on a regular basis.

**Comment by jernst** [comment]
@ethn: Am I correct that in order to restart Decko, I need to `touch restart.txt`? The only one I find is in `/ubos/share/decko/tmpl/restart.txt`. Is that shared among all instances? Or ...?
