### ISSUE TITLE
Reduce log verbosity

### ISSUE THREAD

**Issue by jernst** [decko-commons/decko-ubos#18]
Currently it logs 5 lines to `/var/log/decko/<appconfigid>/production.log` for each successful HTTP request. Turn down to errors and warnings only.

**Comment by ethn** [comment]
We need to set `config.log_level = :warn` in https://github.com/decko-commons/decko-ubos/blob/master/decko/tmpl/application.rb.tmpl.

I'll try to get that out today.

**Comment by ethn** [comment]
We'll definitely get this fixed in the next release.
