### ISSUE TITLE
Decko does not get along with Wordpress

### ISSUE THREAD

**Issue by jernst** [decko-commons/decko-ubos#6]
I created a site with Wordpress at /blog and Decko at /deck. When clicking on the Wordpress icon, going to /blog, instead Decko comes up saying "Could not find /blog".

**Comment by ethn** [comment]
From the email:

I'm a little confused about the error with Decko not getting along with Wordpress; I'm suprised the request could make its way to decko at all.  Is this on a site I have access to?  If not, can you confirm that the appconfig .conf file in /etc/httpd/ubos has "PassengerBaseURI /deck" in it?

There's a lot of code that goes into Decko handling the relative root right once a request gets to it, but if that line is there, I'm not clear on how a root request could even come to Decko in the first place.

But I guess I should ask a bit more about what apache configuration UBOS adds automatically.
Here's Passenger's guide for relative roots: https://www.phusionpassenger.com/library/deploy/apache/deploy/ruby/#deploying-an-app-to-a-sub-uri-or-subdirectory
...and Decko's template for that is here: https://github.com/decko-commons/decko-ubos/blob/master/decko/tmpl/htaccess.tmpl

We don't have all those settings. I was guessing that some equivalent of that Alias command was automatically connecting the sub-URI to the public directory?  All sites have something like that, no?

**Comment by ethn** [comment]
This should be addressed now. I think I confused myself by retaining the name "htaccess" for the fragment template; I was still thinking of it as an htaccess file (at least after having been away from it).

I copied my configuration onto the test server you sent, and it's working there.  What I haven't really tested yet is how it works when decko is the root.  I'm a little concerned about how apache will handle a directive like `Alias / /ubos/lib...`.  If it doesn't like that, we may need enough logic to say "add this if not root context".

I'm attempting an update now in my dev env so I can test it.

**Comment by ethn** [comment]
Yeah, the alias thing broke root decks.  But I can't see errors happening without it, so I commented it out (and wrote some notes to lessen future confusion).  so I think this should be working now.

**Comment by jernst** [comment]
Confirmed fixed.
